[project]
name = "output-reporting"
version = "0.1.0"
description = "Building Performance Output Report Data Model"
authors = [{ name = "IBPSA-USA" }]
requires-python = ">=3.11"
dependencies = ["lattice"]

[dependency-groups]
dev = ["doit", "pytest"]
report = ["jinja2", "matplotlib", "pandas", "pyyaml"]

[tool.uv]
default-groups = ["dev", "report"]

[tool.uv]
package = false

[tool.uv.sources]
lattice = { git = "https://github.com/bigladder/lattice.git", branch = "updates-for-output-reporting" }
