title: "Building Performance Output Report Data Model"
author: "IBPSA-USA"
description: "A standardized modern data model for characterizing building performance output reports"
colors:
  primary: grey
  accent: red
